services:
  api:
    container_name: ${ADMIN_API_CONTAINER_NAME}
    ports:
      - ${ADMIN_EXPOSE_PORT}:5000
    build:
      context: .
      dockerfile: Docker/Dockerfile

    env_file:
      - .env
    command: [
      "poetry", "run", "uvicorn", "app:create_app",
      "--host", "0.0.0.0",
      "--port", '5000',
    ]
  networks:
    - postgres_network
